from pathlib import Path
import json
import warnings

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parents[2]
DATASET_DIR = ROOT / "dataset"
REPORTS_DIR = ROOT / "reports"
FIGURE_DIR = REPORTS_DIR / "figures"
MODELS_DIR = ROOT / "models"

FIGURE_DIR.mkdir(parents=True, exist_ok=True)

INPUT_PATH = DATASET_DIR / "truecar_clean.csv"
MODEL_PATH = MODELS_DIR / "best_advanced_model.joblib"

OUTPUT_PATH = REPORTS_DIR / "price_positioning_classification_report.txt"
CONFUSION_MATRIX_PATH = FIGURE_DIR / "14_price_positioning_confusion_matrix.png"

FEATURES = [
    "Year",
    "Mileage",
    "VehicleAge",
    "MileagePerYear",
    "LogMileage",
    "City",
    "State",
    "Make",
    "Model",
    "MakeModel",
]

TARGET = "Price"


def classify_error(actual: float, predicted: float) -> str:
    # If actual listing price is much higher than model fair value, it is overpriced.
    ratio = (actual - predicted) / predicted

    if ratio > 0.10:
        return "Overpriced"
    if ratio < -0.10:
        return "Underpriced"
    return "Fair"


def main() -> None:
    print("=" * 100)
    print("OPTIONAL CLASSIFICATION LAYER: UNDERPRICED / FAIR / OVERPRICED")
    print("=" * 100)

    df = pd.read_csv(INPUT_PATH, low_memory=False)
    df = df[FEATURES + [TARGET]].dropna().copy()
    df_sample = df.sample(min(100000, len(df)), random_state=42).reset_index(drop=True)

    model = joblib.load(MODEL_PATH)
    preds = model.predict(df_sample[FEATURES])

    df_sample["PredictedFairValue"] = preds
    df_sample["PricePosition"] = [
        classify_error(actual, pred)
        for actual, pred in zip(df_sample[TARGET], df_sample["PredictedFairValue"])
    ]

    print(df_sample["PricePosition"].value_counts())

    # This is not a supervised ground-truth classification task.
    # It is a derived recommendation layer, so we do not report F1/ROC-AUC as primary model metrics.
    report = (
        "This is a derived price-positioning layer, not a ground-truth supervised classifier.\n"
        "Classes are generated by comparing actual listing price with predicted fair market value.\n\n"
        + str(df_sample["PricePosition"].value_counts())
    )

    OUTPUT_PATH.write_text(report, encoding="utf-8")

    counts = df_sample["PricePosition"].value_counts().reindex(["Underpriced", "Fair", "Overpriced"]).fillna(0)

    plt.figure(figsize=(8, 5))
    plt.bar(counts.index, counts.values)
    plt.title("Derived Price Positioning Categories")
    plt.xlabel("Category")
    plt.ylabel("Number of Listings")
    plt.tight_layout()
    plt.savefig(CONFUSION_MATRIX_PATH, dpi=200, bbox_inches="tight")
    plt.close()

    print(f"Saved report to: {OUTPUT_PATH}")
    print(f"Saved category chart to: {CONFUSION_MATRIX_PATH}")


if __name__ == "__main__":
    main()
